#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HookEngine — Language System (TR + EN)
Comprehensive string table for all UI elements
"""

import winreg

REG_PATH = r"Software\YoudTool"

STRINGS = {
    # ==================== TÜRKÇE ====================
    'tr': {
        # ---- APP / WINDOW ----
        'app_title':            "HookEngine v3.0 — HOOK + BELLEK + DLL + HT",
        'app_name':             "HookEngine",
        'version':              "v3.0",
        'status_ready':         "Hazır",
        'status_scanning':      "Taranıyor...",
        'status_done':          "Tamamlandı",
        'status_error':         "Hata",
        'status_attached':      "Bağlı",
        'status_detached':      "Bağlı değil",
        'status_admin':         "Yönetici olarak çalışıyor",
        'status_no_admin':      "Yönetici yetkisi yok",

        # ---- TOP NAVIGATION ----
        'btn_ht_creator':       "HT OLUŞTURUCU",
        'btn_dll_injector':     "DLL ENJEKTÖRÜ",
        'btn_wizard':           "WIZARD",
        'btn_settings':         "AYARLAR",
        'btn_about':            "HAKKINDA",
        'btn_help':             "YARDIM",
        'btn_refresh':          "YENİLE",

        # ---- TAB NAMES ----
        'tab_hook':             "HOOK ANALİZ",
        'tab_memory':           "BELLEK EDİTÖRÜ",
        'tab_ht_table':         "HT TABLOSU",
        'tab_ht_editor':        "HT EDİTÖR",
        'tab_who_writes':       "KİM YAZIYOR?",
        'tab_wizard':           "WIZARD",
        'tab_lua':              "LUA SCRIPT",
        'tab_report':           "RAPOR",
        'tab_settings':         "AYARLAR",
        'tab_console':          "KONSOL",

        # ---- LEFT PANEL — PROCESS LIST ----
        'process_list':         "AÇIK PROCESS'LER",
        'search_placeholder':   "Ara...",
        'refresh':              "YENİLE",
        'select':               "SEÇ",
        'process_none':         "Process: Seçilmedi",
        'process_info':         "Process: {name}\nPID: {pid}\nBellek: {mem:.1f} MB",
        'process_count':        "{count} process",
        'refresh_tooltip':      "Process listesini yenile",
        'select_tooltip':       "Seçili process'i hedefle",

        # ---- TARGET DLL ----
        'target_dll':           "HEDEF DLL:",
        'dll_placeholder':      "GameAssembly.dll",
        'scan_by_dll':          "DLL'E GÖRE TARA",
        'save_ht':              "HT KAYDET",
        'load_ht':              "HT YÜKLE",
        'clear_dll':            "TEMİZLE",

        # ---- HOOK TAB ----
        'chars':                "Karakter:",
        'copy':                 "KOPYALA",
        'quick_scan':           "HIZLI SCAN",
        'full_hook':            "TAM HOOK",
        'important':            "ÖNEMLİ",
        'filtered':             "FİLTRELİ",
        'clear':                "TEMİZLE",
        'stop':                 "DURDUR",
        'save':                 "KAYDET",
        'export':               "DIŞA AKTAR",
        'hook_output':          "Hook Analiz Çıktısı",

        # ---- MEMORY TAB ----
        'type':                 "Tür:",
        'value':                "Değer:",
        'scan':                 "TARA",
        'next_scan':            "YENİDEN TARA",
        'all_values':           "TÜM DEĞERLER",
        'pointer_scan':         "POINTER SCAN",
        'increased':            "ARTIR",
        'decreased':            "AZALT",
        'unchanged':            "DEĞİŞMEYEN",
        'changed':              "DEĞİŞEN",
        'new_value':            "Yeni Değer:",
        'apply_selected':       "SEÇİLİYE UYGULA",
        'apply_visible':        "GÖRÜNENE UYGULA",
        'freeze':               "DONDUR",
        'unfreeze':             "DONDURMAYI DURDUR",
        'add_to_ht':            "HT'YE EKLE",
        'watch':                "İZLE",
        'stop_watch':           "İZLEMEYİ DURDUR",
        'results_count':        "{count} sonuç",
        'hex_value':            "HEX",
        'dec_value':            "DEC",

        # ---- HT TABLE ----
        'ht_current_exe':       "Aktif EXE:",
        'ht_current_table':     "HT Tablosu:",
        'ht_none':              "(yok)",
        'ht_not_selected':      "(seçilmedi)",
        'ht_btn_add':           "Ekle",
        'ht_btn_ok':            "Tamam",
        'ht_btn_clear':         "Temizle",
        'ht_btn_reload':        "Yenile",
        'ht_btn_edit':          "Düzenle",
        'ht_btn_save':          "Kaydet",
        'ht_btn_export':        "Dışa Aktar",
        'ht_how_to_use':        "Oyunu aç → soldan exe seç → Ekle ile .ht seç → Tamam'a bas",
        'ht_loaded_info':       "✓ Yüklendi: {name} — {count} grup. Aktif etmek için 'Tamam'a bas.",
        'ht_created_info':      "✓ Yeni tablo oluşturuldu — {count} grup. 'Tamam' ile aktif et.",
        'ht_enable_all':        "✓ Tümünü Aç",
        'ht_disable_all':       "✗ Tümünü Kapat",
        'ht_freeze_all':        "❄ Tümünü Dondur",
        'ht_unfreeze_all':      "❄ Çöz",
        'ht_run':               "Çalıştır",
        'ht_freeze':            "Dondur",
        'ht_stop':              "Durdur",
        'ht_on':                "AÇIK",
        'ht_off':               "KAPALI",
        'ht_frozen':            "DONMUŞ",

        # ---- HT EDITOR ----
        'editor_title':         "HT EDİTÖR",
        'editor_new':           "Yeni HT",
        'editor_open':          "HT Aç",
        'editor_save':          "Kaydet",
        'editor_save_as':       "Farklı Kaydet",
        'editor_close':         "Kapat",
        'editor_add_group':     "+ Grup Ekle",
        'editor_add_entry':     "+ Entry Ekle",
        'editor_delete':        "Sil",
        'editor_duplicate':     "Kopyala",
        'editor_group_name':    "Grup Adı:",
        'editor_group_color':   "Renk:",
        'editor_label':         "Etiket",
        'editor_read':          "Adres (read)",
        'editor_type':          "Tür",
        'editor_value':         "Değer",
        'editor_mode':          "Mod",
        'editor_hotkey':        "Kısayol",
        'editor_description':   "Açıklama",
        'editor_repeat':        "Döngü (ms)",
        'editor_condition':     "Koşul",
        'editor_formula':       "Formül",
        'editor_script':        "Lua Script",
        'editor_inject':        "Kod Injection",
        'editor_preview':       "Önizleme",
        'editor_validate':      "Doğrula",
        'editor_test':          "Test Et",
        'editor_unsaved':       "Kaydedilmemiş değişiklikler var. Kaydetmek ister misin?",

        # ---- HT ENTRY MODES ----
        'mode_toggle':          "Aç/Kapat",
        'mode_action':          "Tek Seferlik",
        'mode_freeze':          "Dondur",
        'mode_script':          "Lua Script",
        'mode_inject':          "Kod Injection",
        'mode_formula':         "Formül",
        'mode_condition':       "Koşullu",

        # ---- HT ENTRY TYPES ----
        'type_int':             "Tam Sayı (int)",
        'type_float':           "Ondalık (float)",
        'type_double':          "Çift Ondalık (double)",
        'type_byte':            "Bayt (byte)",
        'type_string':          "Metin (string)",
        'type_int64':           "Uzun Sayı (int64)",

        # ---- WHO WRITES ----
        'ww_title':             "KİM YAZIYOR? — Donanım Kesme Noktası Debugger",
        'ww_address_label':     "Hedef Adres (hex):",
        'ww_address_placeholder': "ör: 654F338C",
        'ww_start':             "BAŞLAT",
        'ww_stop':              "DURDUR",
        'ww_clear':             "TEMİZLE",
        'ww_status_idle':       "Bekliyor — adres gir ve BAŞLAT'a bas",
        'ww_status_running':    "Çalışıyor — adrese yazma bekleniyor...",
        'ww_status_stopped':    "Durduruldu",
        'ww_select_process':    "Önce soldan process seç!",
        'ww_invalid_address':   "Geçersiz adres",
        'ww_admin_warning':     "Admin yetkisi gerekli — yönetici olarak çalıştırın",
        'ww_started':           "[+] Debugger başladı — PID {pid}, adres 0x{addr:X}",
        'ww_stopped_info':      "[*] Durduruldu — {count} olay yakalandı",
        'ww_write_detected':    "YAZMA YAKALANDI",
        'ww_thread':            "Thread",
        'ww_rip':               "RIP",
        'ww_module':            "Modül",
        'ww_offset':            "Offset",
        'ww_instruction':       "Komut",
        'ww_registers':         "Register'lar",
        'ww_copy_result':       "KOPYALA",
        'ww_how_to_use':        "Kullanım: Soldan exe seç → adres gir → BAŞLAT → oyunda adrese etkileşim yap",
        'ww_veh_mode':          "VEH Modu (Debugger'sız)",
        'ww_warning_crash':     "Uyarı: Bu mod oyunu çökertebilir. Admin gerekli.",

        # ---- WIZARD ----
        'wz_title':             "WIZARD",
        'wz_welcome':           "Merhaba!\n\nBen HookEngine Wizard. Sana oyun hilesi yapmayı öğreteceğim.\n\nHiçbir şey bilmene gerek yok. Adım adım yönlendireceğim.\n\nHazır mısın?",
        'wz_start':             "Başlayalım →",
        'wz_close':             "Kapat",
        'wz_back':              "← Geri",
        'wz_next':              "Devam →",
        'wz_skip':              "Atla",
        'wz_finish':            "Bitir",
        'wz_check_again':       "Kontrol Et",
        'wz_select_game':       "Önce soldaki listeden bir oyun seçmen lazım.\n\n1. Soldaki listeden oyunu seç\n2. 'SEÇ' butonuna bas\n3. Sonra buraya dön",
        'wz_game_selected':     "Harika!\n\nHedef oyun: {game}\nPID: {pid}\n\nDevam edelim mi?",
        'wz_select_cheat':      "{game} için ne yapmak istiyorsun?\n\nAşağıdaki seçeneklerden birini seç.",
        'wz_no_scenarios':      "{game} için hazır senaryo yok.\n\nKendi isteğini yazabilirsin.",
        'wz_custom':            "Diğer (kendim yazarım)",
        'wz_custom_prompt':     "Tamam! Kendi isteğini yaz.\n\nÖrnek:\n- 'hız 5x yap'\n- 'mermi 999 yap'\n- 'can sınırsız'\n\nNe yapmak istiyorsun?",
        'wz_send':              "Gönder",
        'wz_enter_params':      "Parametreleri gir:",
        'wz_confirm':           "Onayla",
        'wz_confirm_msg':       "Onaylıyor musun?\n\nOyun: {game}\nHile: {cheat}\n\nDevam edersem hile aktif olacak.",
        'wz_run':               "Çalıştır ✓",
        'wz_cancel':            "İptal",
        'wz_running':           "Çalıştırılıyor...\n\n⏳ Hedef process kontrol ediliyor...\n⏳ Adres hesaplanıyor...\n⏳ Değer yazılıyor...\n\nLütfen bekle...",
        'wz_done_msg':          "Hazır! ✅\n\nHile aktif edildi.\n\nOyuna geç ve test et.\n\nÇalıştı mı?",
        'wz_worked':            "Çalıştı ✓",
        'wz_failed':            "Çalışmadı ✗",
        'wz_restart':           "Yeniden Başla",
        'wz_success_msg':       "Mükemmel! 🎉\n\nHile çalışıyor. HT Tablosuna kaydedebilirsin,\nböylece bir daha aynı işlemi yapmana gerek kalmaz.",
        'wz_save_ht':           "HT'ye Kaydet",
        'wz_ok':                "Tamam",
        'wz_saved_ht':          "Kaydedildi! HT Tablosu sekmesinden görebilirsin.",
        'wz_failure_msg':       "Hmm, çalışmadı.\n\nOlası sebepler:\n- Adres değişmiş olabilir\n- Oyun güncellenmiş olabilir\n- Offset yanlış olabilir\n\nTekrar deneyebilirsin.",
        'wz_error_msg':         "Bir hata oluştu:\n\n{reason}",
        'wz_error_no_scenario': "Senaryo bulunamadı",
        'wz_error_no_pid':      "Hedef process seçilmedi",
        'wz_error_open_process': "Process açılamadı (admin gerekli)",
        'wz_error_execution':   "Hile çalıştırılamadı",
        'wz_no_match':          "İsteğin anlaşılamadı.\n\nLütfen farklı kelimelerle tekrar dene.",
        'wz_unknown_error':     "Bilinmeyen hata",

        # ---- LUA ----
        'lua_title':            "LUA SCRIPT",
        'lua_new':              "Yeni Script",
        'lua_open':             "Script Aç",
        'lua_save':             "Kaydet",
        'lua_run':              "ÇALIŞTIR",
        'lua_stop':             "DURDUR",
        'lua_clear':            "TEMİZLE",
        'lua_console':          "Konsol",
        'lua_error':            "Hata",
        'lua_output':           "Çıktı",
        'lua_running':          "Çalışıyor...",
        'lua_stopped':          "Durduruldu",
        'lua_line':             "Satır",
        'lua_api_help':         "Lua API Yardımı",
        'lua_examples':         "Örnekler",
        'lua_saved':            "Script kaydedildi",
        'lua_invalid':          "Geçersiz Lua kodu",

        # ---- REPORT ----
        'report':               "RAPOR",
        'report_save':          "KAYDET",
        'report_clear':         "TEMİZLE",
        'report_generate':      "RAPOR OLUŞTUR",
        'report_export':        "DIŞA AKTAR",
        'report_info':          "Process bilgisi, modüller, thread'ler, hook analizi",
        'report_generating':    "Rapor oluşturuluyor...",
        'report_done':          "Rapor hazır",

        # ---- SETTINGS ----
        'settings_title':       "AYARLAR",
        'settings_language':    "Dil",
        'settings_language_hint': "Arayüz dilini seçin",
        'settings_theme':       "Tema",
        'settings_theme_dark':  "Koyu",
        'settings_theme_light': "Açık",
        'settings_theme_system': "Sistem",
        'settings_font':        "Yazı Tipi",
        'settings_font_size':   "Yazı Boyutu",
        'settings_hotkeys':     "Kısayollar",
        'settings_auto_refresh': "Otomatik Yenileme",
        'settings_auto_refresh_interval': "Yenileme Aralığı (ms)",
        'settings_save':        "KAYDET",
        'settings_reset':       "SIFIRLA",
        'settings_saved':       "Ayarlar kaydedildi",
        'settings_restart_required': "Değişiklikler için yeniden başlatın",
        'settings_admin_required': "Admin yetkisi gerekli",
        'settings_scan_interval': "Tarama Aralığı",
        'settings_max_results': "Maksimum Sonuç",
        'settings_safe_mode':   "Güvenli Mod",
        'settings_safe_mode_hint': "Güvenli Mod — çökmeleri önler, biraz yavaşlatır",

        # ---- LANGUAGE NAMES ----
        'language_tr':          "Türkçe",
        'language_en':          "English",
        'save_settings':        "KAYDET",

        # ---- COMMON DIALOGS ----
        'ok':                   "TAMAM",
        'cancel':               "İPTAL",
        'yes':                  "EVET",
        'no':                   "HAYIR",
        'apply':                "UYGULA",
        'close':                "KAPAT",
        'save':                 "KAYDET",
        'save_as':              "FARKLI KAYDET",
        'open':                 "AÇ",
        'delete':               "SİL",
        'edit':                 "DÜZENLE",
        'copy':                 "KOPYALA",
        'paste':                "YAPIŞTIR",
        'cut':                  "KES",
        'undo':                 "GERİ AL",
        'redo':                 "İLERİ AL",
        'select_all':           "TÜMÜNÜ SEÇ",
        'success':              "BAŞARILI",
        'error':                "HATA",
        'warning':              "UYARI",
        'info':                 "BİLGİ",
        'confirm':              "ONAYLA",
        'loading':              "Yükleniyor...",
        'processing':           "İşleniyor...",
        'please_wait':          "Lütfen bekleyin...",
        'done':                 "Tamamlandı",
        'failed':               "Başarısız",

        # ---- MESSAGES ----
        'ht_saved':             "HT kaydedildi:\n{path}",
        'ht_loaded':            "HT yüklendi:\n{path}",
        'ht_save_failed':       "HT kaydedilemedi:\n{error}",
        'ht_load_failed':       "HT yüklenemedi:\n{error}",
        'warn_select_process':  "Process seç!",
        'warn_select_address':  "Adres seç!",
        'warn_select_entry':    "Entry seç!",
        'warn_invalid_value':   "Geçersiz değer",
        'warn_invalid_address': "Geçersiz adres",
        'warn_admin_required':  "Yönetici yetkisi gerekli",
        'warn_no_process':      "Process seçilmedi",
        'info_copied':          "Kopyalandı",
        'info_copied_count':    "{count} adet kopyalandı",
        'info_frozen_count':    "{count} adres donduruldu",
        'info_applied_count':   "{success} adrese yazıldı",
        'info_applied_bulk':    "{success}/{total} adrese yazıldı",
        'info_freeze_stopped':  "Dondurma durduruldu",
        'info_scan_done':       "Tarama tamamlandı — {count} sonuç",
        'info_scan_started':    "Tarama başladı...",
        'info_scan_empty':      "Sonuç bulunamadı",
        'error_open_process':   "Process açılamadı: {error}",
        'error_read_memory':    "Bellek okunamadı: {error}",
        'error_write_memory':   "Bellek yazılamadı: {error}",
        'error_module_not_found': "Modül bulunamadı: {name}",
        'error_invalid_read':   "Geçersiz read formatı: {read}",

        # ---- TOOLTIPS ----
        'tip_refresh':          "Process listesini yenile",
        'tip_select':           "Seçili process'i hedefle",
        'tip_scan':             "Bellekte değer ara",
        'tip_next_scan':        "Önceki taramayı filtrele",
        'tip_freeze':           "Değeri dondur",
        'tip_add_ht':           "HT tablosuna ekle",
        'tip_load_ht':          "HT dosyası yükle",
        'tip_save_ht':          "HT dosyası kaydet",
        'tip_copy':             "Panoya kopyala",
        'tip_clear':            "Temizle",
        'tip_admin':            "Yönetici olarak çalıştır",
        'tip_hook_scan':        "Hook taraması başlat",
        'tip_who_writes':       "Adrese yazan kodu bul",
        'tip_wizard':           "Sihirbazı aç",
        'tip_settings':         "Ayarları aç",
        'tip_language':         "Dili değiştir",

        # ---- ABOUT ----
        'about_title':          "HAKKINDA",
        'about_version':        "Sürüm",
        'about_author':         "Yapımcı",
        'about_website':        "Web Sitesi",
        'about_github':         "GitHub",
        'about_discord':        "Discord",
        'about_license':        "Lisans",
        'about_description':    "HookEngine — Modern oyun hile aracı\nUnity/IL2CPP ve GoldSrc oyunları için",
        'about_thanks':         "Teşekkürler",

        # ---- HELP ----
        'help_title':           "YARDIM",
        'help_welcome':         "HookEngine'e Hoş Geldiniz",
        'help_intro':           "HookEngine, oyun hileleri yapmak için modern bir araçtır.\n\nAdım adım:\n1. Soldan process seç\n2. Bellek editörü aç\n3. Değer tara (ör: can 100)\n4. Oyunda değeri değiştir (ör: hasar al)\n5. Yeniden tara (ör: 75)\n6. Daralt\n7. Bulunan adresi HT'ye ekle",
        'help_shortcuts':       "Kısayollar",
        'help_faq':             "SSS",
        'help_contact':         "İletişim",

        # ---- MISC ----
        'on':                   "Açık",
        'off':                  "Kapalı",
        'unknown':              "Bilinmiyor",
        'none':                 "Yok",
        'all':                  "Tümü",
        'filter':               "Filtrele",
        'sort':                 "Sırala",
        'ascending':            "Artan",
        'descending':           "Azalan",
        'size':                 "Boyut",
        'date':                 "Tarih",
        'name':                 "İsim",
        'address':              "Adres",
        'value_type':           "Değer Türü",
        'current_value':        "Mevcut Değer",
        'new_value_short':      "Yeni",
        'freeze_status':        "Donma",
        'hotkey_status':        "Kısayol",
        'description_short':    "Açıklama",
        'enabled':              "Etkin",
        'disabled':             "Devre Dışı",
        'ready':                "Hazır",
        'not_ready':            "Hazır Değil",
    },

    # ==================== ENGLISH ====================
    'en': {
        # ---- APP / WINDOW ----
        'app_title':            "HookEngine v3.0 — HOOK + MEMORY + DLL + HT",
        'app_name':             "HookEngine",
        'version':              "v3.0",
        'status_ready':         "Ready",
        'status_scanning':      "Scanning...",
        'status_done':          "Done",
        'status_error':         "Error",
        'status_attached':      "Attached",
        'status_detached':      "Detached",
        'status_admin':         "Running as Administrator",
        'status_no_admin':      "No admin privileges",

        # ---- TOP NAVIGATION ----
        'btn_ht_creator':       "HT CREATOR",
        'btn_dll_injector':     "DLL INJECTOR",
        'btn_wizard':           "WIZARD",
        'btn_settings':         "SETTINGS",
        'btn_about':            "ABOUT",
        'btn_help':             "HELP",
        'btn_refresh':          "REFRESH",

        # ---- TAB NAMES ----
        'tab_hook':             "HOOK ANALYSIS",
        'tab_memory':           "MEMORY EDITOR",
        'tab_ht_table':         "HT TABLE",
        'tab_ht_editor':        "HT EDITOR",
        'tab_who_writes':       "WHO WRITES?",
        'tab_wizard':           "WIZARD",
        'tab_lua':              "LUA SCRIPT",
        'tab_report':           "REPORT",
        'tab_settings':         "SETTINGS",
        'tab_console':          "CONSOLE",

        # ---- LEFT PANEL — PROCESS LIST ----
        'process_list':         "RUNNING PROCESSES",
        'search_placeholder':   "Search...",
        'refresh':              "REFRESH",
        'select':               "SELECT",
        'process_none':         "Process: Not selected",
        'process_info':         "Process: {name}\nPID: {pid}\nMemory: {mem:.1f} MB",
        'process_count':        "{count} processes",
        'refresh_tooltip':      "Refresh process list",
        'select_tooltip':       "Target the selected process",

        # ---- TARGET DLL ----
        'target_dll':           "TARGET DLL:",
        'dll_placeholder':      "GameAssembly.dll",
        'scan_by_dll':          "SCAN BY DLL",
        'save_ht':              "SAVE HT",
        'load_ht':              "LOAD HT",
        'clear_dll':            "CLEAR",

        # ---- HOOK TAB ----
        'chars':                "Characters:",
        'copy':                 "COPY",
        'quick_scan':           "QUICK SCAN",
        'full_hook':            "FULL HOOK",
        'important':            "IMPORTANT",
        'filtered':             "FILTERED",
        'clear':                "CLEAR",
        'stop':                 "STOP",
        'save':                 "SAVE",
        'export':               "EXPORT",
        'hook_output':          "Hook Analysis Output",

        # ---- MEMORY TAB ----
        'type':                 "Type:",
        'value':                "Value:",
        'scan':                 "SCAN",
        'next_scan':            "NEXT SCAN",
        'all_values':           "ALL VALUES",
        'pointer_scan':         "POINTER SCAN",
        'increased':            "INCREASED",
        'decreased':            "DECREASED",
        'unchanged':            "UNCHANGED",
        'changed':              "CHANGED",
        'new_value':            "New Value:",
        'apply_selected':       "APPLY TO SELECTED",
        'apply_visible':        "APPLY TO VISIBLE",
        'freeze':               "FREEZE",
        'unfreeze':             "STOP FREEZE",
        'add_to_ht':            "ADD TO HT",
        'watch':                "WATCH",
        'stop_watch':           "STOP WATCH",
        'results_count':        "{count} results",
        'hex_value':            "HEX",
        'dec_value':            "DEC",

        # ---- HT TABLE ----
        'ht_current_exe':       "Current EXE:",
        'ht_current_table':     "Hack Table:",
        'ht_none':              "(none)",
        'ht_not_selected':      "(not selected)",
        'ht_btn_add':           "Add",
        'ht_btn_ok':            "OK",
        'ht_btn_clear':         "Clear",
        'ht_btn_reload':        "Reload",
        'ht_btn_edit':          "Edit",
        'ht_btn_save':          "Save",
        'ht_btn_export':        "Export",
        'ht_how_to_use':        "Open game → select exe on left → Add .ht file → press OK",
        'ht_loaded_info':       "✓ Loaded: {name} — {count} group(s). Press 'OK' to activate.",
        'ht_created_info':      "✓ New table created — {count} group(s). Press 'OK' to activate.",
        'ht_enable_all':        "✓ Enable All",
        'ht_disable_all':       "✗ Disable All",
        'ht_freeze_all':        "❄ Freeze All",
        'ht_unfreeze_all':      "❄ Unfreeze",
        'ht_run':               "Run",
        'ht_freeze':            "Freeze",
        'ht_stop':              "Stop",
        'ht_on':                "ON",
        'ht_off':               "OFF",
        'ht_frozen':            "FROZEN",

        # ---- HT EDITOR ----
        'editor_title':         "HT EDITOR",
        'editor_new':           "New HT",
        'editor_open':          "Open HT",
        'editor_save':          "Save",
        'editor_save_as':       "Save As",
        'editor_close':         "Close",
        'editor_add_group':     "+ Add Group",
        'editor_add_entry':     "+ Add Entry",
        'editor_delete':        "Delete",
        'editor_duplicate':     "Duplicate",
        'editor_group_name':    "Group Name:",
        'editor_group_color':   "Color:",
        'editor_label':         "Label",
        'editor_read':          "Address (read)",
        'editor_type':          "Type",
        'editor_value':         "Value",
        'editor_mode':          "Mode",
        'editor_hotkey':        "Hotkey",
        'editor_description':   "Description",
        'editor_repeat':        "Repeat (ms)",
        'editor_condition':     "Condition",
        'editor_formula':       "Formula",
        'editor_script':        "Lua Script",
        'editor_inject':        "Code Injection",
        'editor_preview':       "Preview",
        'editor_validate':      "Validate",
        'editor_test':          "Test",
        'editor_unsaved':       "Unsaved changes. Save?",

        # ---- HT ENTRY MODES ----
        'mode_toggle':          "Toggle",
        'mode_action':          "One-shot",
        'mode_freeze':          "Freeze",
        'mode_script':          "Lua Script",
        'mode_inject':          "Code Injection",
        'mode_formula':         "Formula",
        'mode_condition':       "Conditional",

        # ---- HT ENTRY TYPES ----
        'type_int':             "Integer (int)",
        'type_float':           "Float",
        'type_double':          "Double",
        'type_byte':            "Byte",
        'type_string':          "String",
        'type_int64':           "Long (int64)",

        # ---- WHO WRITES ----
        'ww_title':             "WHO WRITES? — Hardware Breakpoint Debugger",
        'ww_address_label':     "Target Address (hex):",
        'ww_address_placeholder': "e.g. 654F338C",
        'ww_start':             "START",
        'ww_stop':              "STOP",
        'ww_clear':             "CLEAR",
        'ww_status_idle':       "Idle — enter address and press START",
        'ww_status_running':    "Running — waiting for writes...",
        'ww_status_stopped':    "Stopped",
        'ww_select_process':    "Select a process from the left panel first!",
        'ww_invalid_address':   "Invalid address",
        'ww_admin_warning':     "Admin privileges required — run as Administrator",
        'ww_started':           "[+] Debugger started — PID {pid}, address 0x{addr:X}",
        'ww_stopped_info':      "[*] Stopped — {count} events captured",
        'ww_write_detected':    "WRITE DETECTED",
        'ww_thread':            "Thread",
        'ww_rip':               "RIP",
        'ww_module':            "Module",
        'ww_offset':            "Offset",
        'ww_instruction':       "Instruction",
        'ww_registers':         "Registers",
        'ww_copy_result':       "COPY",
        'ww_how_to_use':        "Usage: Select exe on left → enter address → START → interact with address in game",
        'ww_veh_mode':          "VEH Mode (No Debugger)",
        'ww_warning_crash':     "Warning: This mode may crash the game. Admin required.",

        # ---- WIZARD ----
        'wz_title':             "WIZARD",
        'wz_welcome':           "Hello!\n\nI'm HookEngine Wizard. I'll teach you how to make game cheats.\n\nYou don't need to know anything. I'll guide you step by step.\n\nReady?",
        'wz_start':             "Let's Start →",
        'wz_close':             "Close",
        'wz_back':              "← Back",
        'wz_next':              "Continue →",
        'wz_skip':              "Skip",
        'wz_finish':            "Finish",
        'wz_check_again':       "Check Again",
        'wz_select_game':       "First select a game from the left list.\n\n1. Select game from left list\n2. Press 'SELECT' button\n3. Then come back here",
        'wz_game_selected':     "Great!\n\nTarget game: {game}\nPID: {pid}\n\nContinue?",
        'wz_select_cheat':      "What do you want to do for {game}?\n\nPick one of the options below.",
        'wz_no_scenarios':      "No scenarios available for {game}.\n\nYou can write your own request.",
        'wz_custom':            "Other (I'll write it)",
        'wz_custom_prompt':     "Okay! Write your request.\n\nExamples:\n- 'speed 5x'\n- 'ammo 999'\n- 'infinite health'\n\nWhat do you want to do?",
        'wz_send':              "Send",
        'wz_enter_params':      "Enter parameters:",
        'wz_confirm':           "Confirm",
        'wz_confirm_msg':       "Confirm?\n\nGame: {game}\nCheat: {cheat}\n\nIf I continue, the cheat will activate.",
        'wz_run':               "Run ✓",
        'wz_cancel':            "Cancel",
        'wz_running':           "Running...\n\n⏳ Checking target process...\n⏳ Calculating address...\n⏳ Writing value...\n\nPlease wait...",
        'wz_done_msg':          "Done! ✅\n\nCheat activated.\n\nGo test in game.\n\nDid it work?",
        'wz_worked':            "Worked ✓",
        'wz_failed':            "Didn't work ✗",
        'wz_restart':           "Restart",
        'wz_success_msg':       "Perfect! 🎉\n\nCheat works. You can save it to HT Table,\nso you don't have to repeat it.",
        'wz_save_ht':           "Save to HT",
        'wz_ok':                "OK",
        'wz_saved_ht':          "Saved! Check HT Table tab.",
        'wz_failure_msg':       "Hmm, didn't work.\n\nPossible reasons:\n- Address may have changed\n- Game may have updated\n- Offset may be wrong\n\nYou can try again.",
        'wz_error_msg':         "An error occurred:\n\n{reason}",
        'wz_error_no_scenario': "Scenario not found",
        'wz_error_no_pid':      "No target process selected",
        'wz_error_open_process': "Could not open process (admin required)",
        'wz_error_execution':   "Could not execute cheat",
        'wz_no_match':          "Couldn't understand your request.\n\nPlease try different words.",
        'wz_unknown_error':     "Unknown error",

        # ---- LUA ----
        'lua_title':            "LUA SCRIPT",
        'lua_new':              "New Script",
        'lua_open':             "Open Script",
        'lua_save':             "Save",
        'lua_run':              "RUN",
        'lua_stop':             "STOP",
        'lua_clear':            "CLEAR",
        'lua_console':          "Console",
        'lua_error':            "Error",
        'lua_output':           "Output",
        'lua_running':          "Running...",
        'lua_stopped':          "Stopped",
        'lua_line':             "Line",
        'lua_api_help':         "Lua API Help",
        'lua_examples':         "Examples",
        'lua_saved':            "Script saved",
        'lua_invalid':          "Invalid Lua code",

        # ---- REPORT ----
        'report':               "REPORT",
        'report_save':          "SAVE",
        'report_clear':         "CLEAR",
        'report_generate':      "GENERATE REPORT",
        'report_export':        "EXPORT",
        'report_info':          "Process info, modules, threads, hook analysis",
        'report_generating':    "Generating report...",
        'report_done':          "Report ready",

        # ---- SETTINGS ----
        'settings_title':       "SETTINGS",
        'settings_language':    "Language",
        'settings_language_hint': "Choose the interface language",
        'settings_theme':       "Theme",
        'settings_theme_dark':  "Dark",
        'settings_theme_light': "Light",
        'settings_theme_system': "System",
        'settings_font':        "Font",
        'settings_font_size':   "Font Size",
        'settings_hotkeys':     "Hotkeys",
        'settings_auto_refresh': "Auto Refresh",
        'settings_auto_refresh_interval': "Refresh Interval (ms)",
        'settings_save':        "SAVE",
        'settings_reset':       "RESET",
        'settings_saved':       "Settings saved",
        'settings_restart_required': "Restart required for changes",
        'settings_admin_required': "Admin privileges required",
        'settings_scan_interval': "Scan Interval",
        'settings_max_results': "Max Results",
        'settings_safe_mode':   "Safe Mode",
        'settings_safe_mode_hint': "Safe Mode — prevents crashes, slightly slower",

        # ---- LANGUAGE NAMES ----
        'language_tr':          "Türkçe",
        'language_en':          "English",
        'save_settings':        "SAVE",

        # ---- COMMON DIALOGS ----
        'ok':                   "OK",
        'cancel':               "CANCEL",
        'yes':                  "YES",
        'no':                   "NO",
        'apply':                "APPLY",
        'close':                "CLOSE",
        'save':                 "SAVE",
        'save_as':              "SAVE AS",
        'open':                 "OPEN",
        'delete':               "DELETE",
        'edit':                 "EDIT",
        'copy':                 "COPY",
        'paste':                "PASTE",
        'cut':                  "CUT",
        'undo':                 "UNDO",
        'redo':                 "REDO",
        'select_all':           "SELECT ALL",
        'success':              "SUCCESS",
        'error':                "ERROR",
        'warning':              "WARNING",
        'info':                 "INFO",
        'confirm':              "CONFIRM",
        'loading':              "Loading...",
        'processing':           "Processing...",
        'please_wait':          "Please wait...",
        'done':                 "Done",
        'failed':               "Failed",

        # ---- MESSAGES ----
        'ht_saved':             "HT saved:\n{path}",
        'ht_loaded':            "HT loaded:\n{path}",
        'ht_save_failed':       "HT save failed:\n{error}",
        'ht_load_failed':       "HT load failed:\n{error}",
        'warn_select_process':  "Select a process!",
        'warn_select_address':  "Select an address!",
        'warn_select_entry':    "Select an entry!",
        'warn_invalid_value':   "Invalid value",
        'warn_invalid_address': "Invalid address",
        'warn_admin_required':  "Admin privileges required",
        'warn_no_process':      "No process selected",
        'info_copied':          "Copied",
        'info_copied_count':    "{count} items copied",
        'info_frozen_count':    "{count} addresses frozen",
        'info_applied_count':   "{success} addresses written",
        'info_applied_bulk':    "{success}/{total} addresses written",
        'info_freeze_stopped':  "Freeze stopped",
        'info_scan_done':       "Scan complete — {count} results",
        'info_scan_started':    "Scan started...",
        'info_scan_empty':      "No results found",
        'error_open_process':   "Could not open process: {error}",
        'error_read_memory':    "Could not read memory: {error}",
        'error_write_memory':   "Could not write memory: {error}",
        'error_module_not_found': "Module not found: {name}",
        'error_invalid_read':   "Invalid read format: {read}",

        # ---- TOOLTIPS ----
        'tip_refresh':          "Refresh process list",
        'tip_select':           "Target selected process",
        'tip_scan':             "Scan memory for value",
        'tip_next_scan':        "Filter previous scan",
        'tip_freeze':           "Freeze value",
        'tip_add_ht':           "Add to HT table",
        'tip_load_ht':          "Load HT file",
        'tip_save_ht':          "Save HT file",
        'tip_copy':             "Copy to clipboard",
        'tip_clear':            "Clear",
        'tip_admin':            "Run as administrator",
        'tip_hook_scan':        "Start hook scan",
        'tip_who_writes':       "Find what writes to address",
        'tip_wizard':           "Open wizard",
        'tip_settings':         "Open settings",
        'tip_language':         "Change language",

        # ---- ABOUT ----
        'about_title':          "ABOUT",
        'about_version':        "Version",
        'about_author':         "Author",
        'about_website':        "Website",
        'about_github':         "GitHub",
        'about_discord':        "Discord",
        'about_license':        "License",
        'about_description':    "HookEngine — Modern game hacking suite\nFor Unity/IL2CPP and GoldSrc games",
        'about_thanks':         "Thanks",

        # ---- HELP ----
        'help_title':           "HELP",
        'help_welcome':         "Welcome to HookEngine",
        'help_intro':           "HookEngine is a modern tool for making game cheats.\n\nStep by step:\n1. Select process on left\n2. Open Memory Editor\n3. Scan for value (e.g. health 100)\n4. Change value in game (e.g. take damage)\n5. Rescan (e.g. 75)\n6. Narrow down\n7. Add found address to HT",
        'help_shortcuts':       "Shortcuts",
        'help_faq':             "FAQ",
        'help_contact':         "Contact",

        # ---- MISC ----
        'on':                   "On",
        'off':                  "Off",
        'unknown':              "Unknown",
        'none':                 "None",
        'all':                  "All",
        'filter':               "Filter",
        'sort':                 "Sort",
        'ascending':            "Ascending",
        'descending':           "Descending",
        'size':                 "Size",
        'date':                 "Date",
        'name':                 "Name",
        'address':              "Address",
        'value_type':           "Value Type",
        'current_value':        "Current Value",
        'new_value_short':      "New",
        'freeze_status':        "Freeze",
        'hotkey_status':        "Hotkey",
        'description_short':    "Description",
        'enabled':              "Enabled",
        'disabled':             "Disabled",
        'ready':                "Ready",
        'not_ready':            "Not Ready",
    }
}

# Cached current language
_current_lang = None


def get_saved_language():
    """Read language from registry. Default: en"""
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH)
        lang, _ = winreg.QueryValueEx(key, "Language")
        winreg.CloseKey(key)
        if lang in ('tr', 'en'):
            return lang
    except Exception:
        pass
    return 'en'


def save_language(lang):
    """Save language to registry"""
    try:
        key = winreg.CreateKey(winreg.HKEY_CURRENT_USER, REG_PATH)
        winreg.SetValueEx(key, "Language", 0, winreg.REG_SZ, lang)
        winreg.CloseKey(key)
        global _current_lang
        _current_lang = lang
        return True
    except Exception:
        return False


def set_current(lang):
    """Set active language for this session"""
    global _current_lang
    if lang in ('tr', 'en'):
        _current_lang = lang


def current():
    """Get active language"""
    global _current_lang
    if _current_lang is None:
        _current_lang = get_saved_language()
    return _current_lang


def t(key, **kwargs):
    """Translate key with format placeholders"""
    lang = current()
    text = STRINGS.get(lang, STRINGS['en']).get(key, STRINGS['en'].get(key, key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text


def has_key(key):
    """Check if key exists in current language"""
    lang = current()
    return key in STRINGS.get(lang, {}) or key in STRINGS['en']